stages:
  - production

#Production stage
production:
   stage: production
   before_script:
     - apk update
     - apk upgrade
     - apk add bash
     - apk add openssh
     - apk add openssh-client
     - mkdir -p ~/.ssh
     - eval "$(ssh-agent -s)"
     - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
     - chmod 700 ~/.ssh
     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   script:
     - ssh -o ubuntu@ec2-15-164-204-203.ap-northeast-2.compute.amazonaws.com "forever stopall && cd dodamshindam/backend && git checkout develop && git pull && pip3 install -r requirements.txt &&nohup python3 app.py &"

   environment:
     name: production
     url: https://www.api-stride.com
