stages:
  - test
  - deploy

before_script:
  - apk update
  - apk upgrade
  - apk add bash


#Test stage
test:
  stage: test
  only:
    - develop
  script: echo 'Api test'

#Production stage
deploy:
   stage: deploy
   only:
     changes:
       - "**/backend/*"

   before_script:
     - apk add openssh
     - apk add openssh-client
     - eval "$(ssh-agent -s)"
     - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
     - mkdir -p ~/.ssh
     - chmod 700 ~/.ssh
   script:
     - ssh -o StrictHostKeyChecking=no ubuntu@ec2-15-164-204-203.ap-northeast-2.compute.amazonaws.com "sudo pkill python3; cd dodamshindam; sudo git checkout develop; sudo git pull; cd backend; nohup python3 app.py > /dev/null 2>&1 &"

   environment:
     name: deploy
     url: https://www.api-stride.com
