stages:
  - production

#Production stage
production:
   stage: production
   before_script:
     - apk update
     - apk upgrade
     - apk add bash
     - apk add openssh
     - mkdir -p ~/.ssh
     - echo -e "$PRIVATE_KEY" > ~/.ssh/id_rsa
     - chmod 700 ~/.ssh
     - chmod 600 ~/.ssh/id_rsa
     - eval "$(ssh-agent -s)"
     - ssh-add ~/.ssh/id_rsa
     - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts

     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   script:
      - bash .gitlab-deploy-prod.sh

   environment:
     name: production
     url: https://www.api-stride.com
