stages:
  - deploy_aws

production:
  stage: deploy_aws

  only:
    - develop

  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - bash .gitlab-deploy-prod.sh

  environment:
    name: production

