stages:
  - deploy_aws

production:
  stage: deploy_aws

  only:
    - develop

  before_script:
    - apk update
    - apk upgrade
    - apk add bash
    - apk add openssh
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - echo -e "$PRIVATE_KEY" > ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash ./.gitlab-deploy-prod.sh

  environment:
    name: production

