name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versifoning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  # flutter_svg: 0.14.0
  firebase_core: ^0.5.0
  firebase_remote_config: ^0.4.0
  firebase_auth: ^0.18.0+1
  apple_sign_in: ^0.1.0
  
  firebase_crashlytics: ^0.1.4+1
  firebase_analytics: ^6.0.0
  firebase_messaging: ^7.0.0
  uuid: ^2.2.2

  provider: ^4.3.1
  # provider: ^3.0.0
  font_awesome_flutter: ^8.8.1
  flutter_auth_buttons: ^0.8.0
  webview_flutter: ^1.0.0
  carousel_slider: ^2.2.1
  modal_bottom_sheet: ^0.2.0+1
  awesome_dialog: ^1.1.3
  #fancy_shimmer_image: ^1.2.0

  kakao_flutter_sdk: ^0.5.0
  dio: ^3.0.10
  # json_annotation: ^3.0.1
  # package_info: ^0.4.1
  # platform: ^2.2.1
  # shared_preferences: ^0.5.8
  
  flutter_secure_storage: ^3.3.3
  #sleek_circular_slider: ^1.1.0
  cached_network_image: ^2.2.0+1
  rxdart: ^0.24.1
  tutorial_coach_mark: ^0.5.1
  #flutter_sliding_tutorial: ^0.1.0
  #animations: ^1.1.2
  #intro_slider: ^2.3.1
  #flutter_range_slider: ^1.4.0
  flutter_svg: ^0.18.1
  animated_widgets: ^1.0.6
  flutter_launcher_icons: ^0.7.5
  loading: ^1.0.2
  custom_switch: ^0.0.1
  pull_to_refresh: ^1.6.1

  #flutter_staggered_grid_view: ^0.3.2
  # flutter_is_emulator: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/dislike_button.png
    - assets/dislike_button_s.png

    - assets/heart_button.png
    - assets/heart_button_s.png
    - assets/star_button.png
    - assets/purple_star.png
    - assets/purple_folder.png
    - assets/swipe_dislike.png
    - assets/swipe_heart.png
    - assets/stride_text_logo.png
    - assets/buy.png
    - assets/like-of-filled-heart.png
    - assets/close_purple.png
    - assets/right-arrow.png
    - assets/heart.svg 
    - assets/search.png
    - assets/collection.png
    - assets/collection_s.png
    - assets/heart.png 
    - assets/heart_s.png 
    - assets/home.png 
    - assets/home_s.png 
    - assets/user.png
    - assets/user_s.png
    - assets/config.png
    - assets/left-arrow.svg
    - assets/right.png
    - assets/shopping-bag.svg
    - assets/shopping-bag.png
    - assets/shopping-bag@2x.png
    - assets/filter.png



    - images/store.png
    - images/love.png
    - images/fashion.png
    - images/intro.png
    - images/intro.jpg

    - images/kakao_login.png
    # - images/swipe.png
    # - images/tap.png
    # - images/ruler.png
    - images/fix.png
    - images/folder_plus.png
    - images/remove.png
    - images/left-arrow.png
    # - images/up-arrow.png
    - images/trash.svg
    - images/folder.svg
    - images/edit.svg
    - images/buy.svg
    # - images/ruler.svg
    - images/menu_heart.svg
    - images/menu_swipe.svg
    - images/menu_lookbook.svg
    - images/menu_mypage.svg
    - images/times.svg
    - images/like.svg
    - images/icon.png
    - images/stride_text.png
    - images/filter.png
    # - images/a.png
    # - images/loading.gif
    # - images/loading_white.gif
    - images/search.png
    # - images/swipe_image_logo.jpg

  fonts:
    - family: Nanum
      fonts:
      - asset: assets/fonts/NanumSquareRoundR.ttf
      - asset: assets/fonts/NanumSquareRoundEB.ttf
        weight: 700
      



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
